#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionFourward.Core.Dataverse
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum nx_operationalisierung
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0 = 125060000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1 = 125060001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2 = 125060002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_3 = 125060003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_4 = 125060004,
	}
}
#pragma warning restore CS1591
