#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace MissionFourward.Core.Dataverse
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class CrmOrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmOrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MissionFourward.Core.Dataverse.nx_PostFinBewertungen"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MissionFourward.Core.Dataverse.nx_PostFinBewertungen> nx_PostFinBewertungenSet
		{
			get
			{
				return this.CreateQuery<MissionFourward.Core.Dataverse.nx_PostFinBewertungen>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MissionFourward.Core.Dataverse.nx_PostFinProject"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MissionFourward.Core.Dataverse.nx_PostFinProject> nx_PostFinProjectSet
		{
			get
			{
				return this.CreateQuery<MissionFourward.Core.Dataverse.nx_PostFinProject>();
			}
		}
	}
}
#pragma warning restore CS1591
