#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionFourward.Core.Dataverse
{
	
	
	/// <summary>
	/// Status of the PostFinBewertungen
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum nx_postfinbewertungen_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the PostFinBewertungen
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum nx_postfinbewertungen_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("nx_postfinbewertungen")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class nx_PostFinBewertungen : Microsoft.Xrm.Sdk.Entity
	{
		
				/// <summary>
		/// Available fields, a the time of codegen, for the nx_postfinbewertungen entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string nx_3_1_1_StrategieFit = "nx_3_1_1_strategiefit";
			public const string nx_3_1_1_strategiefitName = "nx_3_1_1_strategiefitname";
			public const string nx_3_2_1_internBeduerfnis = "nx_3_2_1_internbeduerfnis";
			public const string nx_3_2_1_internbeduerfnisName = "nx_3_2_1_internbeduerfnisname";
			public const string nx_3_2_2_externBeduerfnis = "nx_3_2_2_externbeduerfnis";
			public const string nx_3_2_2_externbeduerfnisName = "nx_3_2_2_externbeduerfnisname";
			public const string nx_3_3_1_Datenorganisierbar = "nx_3_3_1_datenorganisierbar";
			public const string nx_3_3_1_datenorganisierbarName = "nx_3_3_1_datenorganisierbarname";
			public const string nx_3_4_1_UmsetzungsdauerTimetoMarket = "nx_3_4_1_umsetzungsdauertimetomarket";
			public const string nx_3_4_1_umsetzungsdauertimetomarketName = "nx_3_4_1_umsetzungsdauertimetomarketname";
			public const string nx_3_4_2_Nutzerfreundlichkeit = "nx_3_4_2_nutzerfreundlichkeit";
			public const string nx_3_4_2_nutzerfreundlichkeitName = "nx_3_4_2_nutzerfreundlichkeitname";
			public const string nx_HypeProjekt = "nx_hypeprojekt";
			public const string nx_HypeProjektName = "nx_hypeprojektname";
			public const string nx_Name = "nx_name";
			public const string nx_PostFinBewertungenId = "nx_postfinbewertungenid";
			public const string Id = "nx_postfinbewertungenid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string nx_postfinbewertungen_HypeProjekt_nx_postfinproject = "nx_postfinbewertungen_HypeProjekt_nx_postfinproject";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public nx_PostFinBewertungen() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "nx_postfinbewertungen";
		
		public const string EntityLogicalCollectionName = "nx_postfinbewertungens";
		
		public const string EntitySetName = "nx_postfinbewertungens";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Passt die Initiative in die unternehmensstrategische Ausrichtung der Organisation (Unternehmens-, Daten-, AI-, IT-Strategie etc.)?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_1_1_strategiefit")]
		public virtual nx_operationalisierung? nx_3_1_1_StrategieFit
		{
			get
			{
				return ((nx_operationalisierung?)(EntityOptionSetEnum.GetEnum(this, "nx_3_1_1_strategiefit")));
			}
			set
			{
				this.SetAttributeValue("nx_3_1_1_strategiefit", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_1_1_strategiefitname")]
		public string nx_3_1_1_strategiefitName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_3_1_1_strategiefit"))
				{
					return this.FormattedValues["nx_3_1_1_strategiefit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Wie stark ist das Bedürfnis oder die Nachfrage nach der Initiative seitens der Organisation beispielsweise auf Basis der Mitarbeitendenbedürfnisse oder zu lösender Problemstellungen in der Organisation?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_2_1_internbeduerfnis")]
		public virtual nx_operationalisierung? nx_3_2_1_internBeduerfnis
		{
			get
			{
				return ((nx_operationalisierung?)(EntityOptionSetEnum.GetEnum(this, "nx_3_2_1_internbeduerfnis")));
			}
			set
			{
				this.SetAttributeValue("nx_3_2_1_internbeduerfnis", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_2_1_internbeduerfnisname")]
		public string nx_3_2_1_internbeduerfnisName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_3_2_1_internbeduerfnis"))
				{
					return this.FormattedValues["nx_3_2_1_internbeduerfnis"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Wie stark ist das Bedürfnis oder die Nachfrage nach der Initiative seitens externer Stakeholder der Organisation wie beispielsweise durch Kunden, Partner und Supplier, Kapitalgeber oder sonstige Stakeholder?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_2_2_externbeduerfnis")]
		public virtual nx_operationalisierung? nx_3_2_2_externBeduerfnis
		{
			get
			{
				return ((nx_operationalisierung?)(EntityOptionSetEnum.GetEnum(this, "nx_3_2_2_externbeduerfnis")));
			}
			set
			{
				this.SetAttributeValue("nx_3_2_2_externbeduerfnis", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_2_2_externbeduerfnisname")]
		public string nx_3_2_2_externbeduerfnisName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_3_2_2_externbeduerfnis"))
				{
					return this.FormattedValues["nx_3_2_2_externbeduerfnis"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sind die für die Initiative notwendigen Daten in hinreichender Qualität organisierbar (vorhanden, erhebbar, erwerbbar)?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_3_1_datenorganisierbar")]
		public virtual nx_operationalisierung? nx_3_3_1_Datenorganisierbar
		{
			get
			{
				return ((nx_operationalisierung?)(EntityOptionSetEnum.GetEnum(this, "nx_3_3_1_datenorganisierbar")));
			}
			set
			{
				this.SetAttributeValue("nx_3_3_1_datenorganisierbar", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_3_1_datenorganisierbarname")]
		public string nx_3_3_1_datenorganisierbarName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_3_3_1_datenorganisierbar"))
				{
					return this.FormattedValues["nx_3_3_1_datenorganisierbar"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Ist aufgrund der zu erwartenden Umsetzungsdauer die Initiative realisierbar?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_4_1_umsetzungsdauertimetomarket")]
		public virtual nx_operationalisierung? nx_3_4_1_UmsetzungsdauerTimetoMarket
		{
			get
			{
				return ((nx_operationalisierung?)(EntityOptionSetEnum.GetEnum(this, "nx_3_4_1_umsetzungsdauertimetomarket")));
			}
			set
			{
				this.SetAttributeValue("nx_3_4_1_umsetzungsdauertimetomarket", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_4_1_umsetzungsdauertimetomarketname")]
		public string nx_3_4_1_umsetzungsdauertimetomarketName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_3_4_1_umsetzungsdauertimetomarket"))
				{
					return this.FormattedValues["nx_3_4_1_umsetzungsdauertimetomarket"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Ist die Initiative so umsetzbar, dass sie von ihren Nutzern vertretbar verwendet werden kann?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_4_2_nutzerfreundlichkeit")]
		public virtual nx_operationalisierung? nx_3_4_2_Nutzerfreundlichkeit
		{
			get
			{
				return ((nx_operationalisierung?)(EntityOptionSetEnum.GetEnum(this, "nx_3_4_2_nutzerfreundlichkeit")));
			}
			set
			{
				this.SetAttributeValue("nx_3_4_2_nutzerfreundlichkeit", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_3_4_2_nutzerfreundlichkeitname")]
		public string nx_3_4_2_nutzerfreundlichkeitName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_3_4_2_nutzerfreundlichkeit"))
				{
					return this.FormattedValues["nx_3_4_2_nutzerfreundlichkeit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_hypeprojekt")]
		public Microsoft.Xrm.Sdk.EntityReference nx_HypeProjekt
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("nx_hypeprojekt");
			}
			set
			{
				this.SetAttributeValue("nx_hypeprojekt", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_hypeprojektname")]
		public string nx_HypeProjektName
		{
			get
			{
				if (this.FormattedValues.Contains("nx_hypeprojekt"))
				{
					return this.FormattedValues["nx_hypeprojekt"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_name")]
		public string nx_Name
		{
			get
			{
				return this.GetAttributeValue<string>("nx_name");
			}
			set
			{
				this.SetAttributeValue("nx_name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_postfinbewertungenid")]
		public System.Nullable<System.Guid> nx_PostFinBewertungenId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("nx_postfinbewertungenid");
			}
			set
			{
				this.SetAttributeValue("nx_postfinbewertungenid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_postfinbewertungenid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.nx_PostFinBewertungenId = value;
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the PostFinBewertungen
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual nx_postfinbewertungen_statecode? statecode
		{
			get
			{
				return ((nx_postfinbewertungen_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the PostFinBewertungen
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual nx_postfinbewertungen_statuscode? statuscode
		{
			get
			{
				return ((nx_postfinbewertungen_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 nx_postfinbewertungen_HypeProjekt_nx_postfinproject
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nx_hypeprojekt")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("nx_postfinbewertungen_HypeProjekt_nx_postfinproject")]
		public MissionFourward.Core.Dataverse.nx_PostFinProject nx_postfinbewertungen_HypeProjekt_nx_postfinproject
		{
			get
			{
				return this.GetRelatedEntity<MissionFourward.Core.Dataverse.nx_PostFinProject>("nx_postfinbewertungen_HypeProjekt_nx_postfinproject", null);
			}
			set
			{
				this.SetRelatedEntity<MissionFourward.Core.Dataverse.nx_PostFinProject>("nx_postfinbewertungen_HypeProjekt_nx_postfinproject", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
